// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#include "telegrambottypeobject.h"

const TelegramBotTypeObject::Null TelegramBotTypeObject::null = TelegramBotTypeObject::Null();
qint64 TelegramBotTypeObject::mConstructedCount = 0;

TelegramBotTypeObject::TelegramBotTypeObject() :
    mError(false),
    mNull(false)
{
    mConstructedCount++;
}

TelegramBotTypeObject::TelegramBotTypeObject(const Null&) :
    mError(false),
    mNull(true)
{
}

TelegramBotTypeObject::~TelegramBotTypeObject()
{
    mConstructedCount--;
}

